### PR TITLE
Added toastr

### PR DESCRIPTION
**Pull request by scandal47**
Duplicated title and subtitle fixup

### CODE REVIEW

**Comment by shime** [comment]
I don't see notifications when copying with this change.

**Comment by scandal47** [comment]
You are testing this on Safari? Because someone reported on #40 that Clipboard is not working, and toastr is triggered inside Clipboard success callback, so if Clipboard is not working then toastr can't be triggered neither.

**Comment by shime** [comment]
Nope, on Chrome.

**Comment by vlado** [comment]
It was issue on my side, I had JS error (missing dependency)

**Comment by shime** [comment]
@vlado can you test this PR on your machine?

**Comment by vlado** [comment]
> @vlado can you test this PR on your machine?

Will do

**Comment by vlado** [comment]
> @vlado can you test this PR on your machine?

Works fine in Safari and Chrome.

Screenshot 2020-12-31 at 14 34 51

@shime Should I merge or you wanna see what is wrong on your machine.

**Review by vlado — COMMENTED** [review]
Looks and works much better then alert but not sure if we should use https://rfoel.github.io/bulma-toast/ instead?

**Comment by scandal47** [comment]
> Looks and works much better then alert but not sure if we should use https://rfoel.github.io/bulma-toast/ instead?

I saw Bulma toast but toastr seems much better and with more options, Bulma toast needs more styling also.

**Comment by vlado** [comment]
> > Looks and works much better then alert but not sure if we should use https://rfoel.github.io/bulma-toast/ instead?
> 
> I saw Bulma toast (and tested it) but toastr seems much better and with more options, Bulma toast needs more styling also.

@Macxim what is your opinion on this?

**Comment by scandal47** [comment]
Also, on Bulma toast animations don't work out of the box, so one more dependency needed for it to work :D

**Comment by berislavbabic** [comment]
Works fine for me. Way better than the alert thing.

**Comment by Macxim** [comment]
https://rfoel.github.io/bulma-toast/ looks much nicer indeed but I guess this is a good start.

**Comment by Macxim** [comment]
I do like the fact that it's using Bulma's markup and styling so we don't need extra CSS on top of the framework.

**Comment by vlado** [comment]
> I do like the fact that it's using Bulma's markup and styling so we don't need extra CSS on top of the framework.

Same here.

I've merge it cause it is much better the current alert. We can switch to bulimia latter when/if needed.

**Comment by Macxim** [comment]
Agree.

**Pull request merged**
