### PR TITLE
makefile: add makefile helper and app description

### PR DESCRIPTION
**Pull request by Xenosb**

### CODE REVIEW

**Comment by berislavbabic** [comment]
Do we need to use make if we already have rake and rails tasks?

**Comment by Xenosb** [comment]
Not really but it's here as a simple helper. Developers/designers/testers can start developing by running 3 super simple commands and without much hustle.

```bash
make build
make db-create
make server
```

**Comment by Xenosb** [comment]
For simplicity we also have few more 'shortcuts', all of them super self explanatory 
```bash
make bash
make db-psql 
make db-rollback
make db-migrate
make rails-console
```

**Comment by fsuste** [comment]
> Do we need to use make if we already have rake and rails tasks?

No, but I don't mind them personally. This can probably help someone who's not from the rails world as much.

**Review by fsuste — APPROVED** [review]

**Pull request merged**
