### PR TITLE
Add nicer hero and rework filters

### LINKED ISSUE #69: Add real hero section
I have a suggestion. I'll post something quickly.

### PR DESCRIPTION
**Pull request by Macxim**
Closes #69 

- I added a background pattern on a dark background.
- I placed the main call to action button inside the hero.
- I don't think filters should be hidden by default. And clicking a button to show filters was a bit weird in this context IMO.

### Preview

Screen Shot 2021-01-01 at 16 29 01

Let me know what you think.

### CODE REVIEW

**Review by vlado — COMMENTED** [review]
Big 👍 

I'm only not sure about filters not beinig hidden by default. I also prefer the visible by default but the reason why I did it is to have ads visible when page is loaded ob mobile.

Screenshot 2021-01-02 at 00 49 50

**Comment by vlado** [comment]
> Big 👍
> 
> I'm only not sure about filters not beinig hidden by default. I also prefer the visible by default but the reason why I did it is to have ads visible when page is loaded ob mobile.

Maybe we should have them visible on desktop and hidden on mobile?

**Comment by Macxim** [comment]
Alright, that makes sense.

**Comment by Macxim** [comment]
@vlado Updated, can you check?

**Review by vlado — APPROVED** [review]
Looks awesome 👍

**Pull request merged**
