### PR TITLE
GitHub actions - lint workflow

### PR DESCRIPTION
**Pull request by vlado**
Setup GitHub actions workflow to run Rubocop.

### CODE REVIEW

**Review by berislavbabic — APPROVED** [review]

**Review by berislavbabic — APPROVED** [review]
Looks great, we can extend this when someone decides it's time to add some tests :trollface:

**Comment by vlado** [comment]
I'll merge this now so we have Rubocop running ASAP. Feel free to fork and improve as needed.

@shime Can we run ESlint here also?

**Comment by shime** [comment]
@vlado of course, I'll add it.

**Comment by vlado** [comment]
> @vlado of course, I'll add it.

Can you also add caching for bundle installl 🙏

**Pull request merged**
