### PR TITLE
Redirect all traffic to www.potres-petrinja.hr and force ssl.

### PR DESCRIPTION
**Pull request by vlado**
We are redirecting all request to SSL in Cloudflare so we just need
to redirect eveything to www subdomain on app level

Closes https://github.com/vlado/earthquake-croatia/issues/37

### CODE REVIEW

**Comment by vlado** [comment]
Do not merge yet. Looks like we can redirect to www on Cloudflare also.

**Comment by vlado** [comment]
Cloudflare will redirect `potres-petrinja.hr` to `www.potres-petrinja.hr` but we still need this for `potres.herokuapp.com` so this os ready for review and deployment.

**Comment by shime** [comment]
Looks good. Let's test it in production. :trollface:

**Comment by vlado** [comment]
> Looks good. Let's test it in production. :trollface:

😈

**Comment by vlado** [comment]
Doesn't work, rolling back

**Comment by shime** [comment]
Works fine on my machine.

**Comment by vlado** [comment]
Solved in https://github.com/vlado/earthquake-croatia/commit/edd420b401566beb1520321babbbd4ee8d2ec76e

**Pull request merged**
