### PR TITLE
Remove inline styles

### LINKED ISSUE #58: Stop using inline styles
Instead of adding `style="margin-bottom: 40px"` and similar, we should use Bulma's helpers like `class="mb-3"`.

### PR DESCRIPTION
**Pull request by Macxim**
Remove inline styles in favor of Bulma's helpers

### CODE REVIEW

**Comment by Macxim** [comment]
See #58

**Review by fsuste — APPROVED** [review]

**Comment by vlado** [comment]
This is great @Macxim

There are some conflicts with changes in https://github.com/vlado/earthquake-croatia/pull/53. Are you comfortable with resolving those or want me to do it?

**Comment by Macxim** [comment]
Done! Sorry for the delay.

**Comment by vlado** [comment]
> Done! Sorry for the delay.

👍 New conflict :(

**Comment by Macxim** [comment]
There you go 😉

**Comment by vlado** [comment]
Thanks @Macxim

Can you give your opinion on https://github.com/vlado/earthquake-croatia/pull/47#issuecomment-752976189

**Pull request merged**
