### PR TITLE
Remove fontawesome in favor of inline svg

### LINKED ISSUE #73: Replace FontAwesome icon font with SVG
We're loading tons of CSS only for using a single icon. 
I can take care of it.

### PR DESCRIPTION
**Pull request by Macxim**
Closes #73

### CODE REVIEW

**Review by vlado — APPROVED** [review]
:shipit:

**Comment by vlado** [comment]
Icon is not visible for me on production

Screenshot 2021-01-02 at 12 47 29

**Comment by vlado** [comment]
> Icon is not visible for me on production
> 
> Screenshot 2021-01-02 at 12 47 29

Same on mobile

**Comment by Macxim** [comment]
Will fix now! @vlado

**Comment by Macxim** [comment]
Fixed in #83

**Pull request merged**
